name: surf_places
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cached_network_image: 3.4.1
  collection: 1.19.1
  cupertino_icons: ^1.0.8
  dio: 5.8.0+1
  drift: 2.27.0
  drift_flutter: 0.2.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_svg: 2.2.0
  freezed_annotation: ^2.4.1
  json_annotation: 4.9.0
  path: 1.9.1
  path_provider: 2.1.5
  provider: 6.1.5
  retrofit: ^4.6.0
  rxdart: 0.28.0
  shared_preferences: ^2.5.3
  sqlite3_flutter_libs: 0.5.34

dev_dependencies:
  build_runner: ^2.5.4
  drift_dev: 2.27.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.9.5
  retrofit_generator: ^9.6.0
  surf_dcm_presets: 1.0.0
  surf_lint_rules: 4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/catalog/
    - assets/images/
    - assets/json/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700